# Generated by Django 4.2.4 on 2023-10-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_newslatter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='messages',
        ),
    ]
