# Generated by Django 4.2.4 on 2023-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_rename_massage_contact_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pic', models.ImageField(upload_to='uploads/testimonial')),
            ],
        ),
    ]
